### ISSUE TITLE
Parallelize Conpair concordance

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/Conpair#3]
[This function](https://github.com/mskcc/Conpair/blob/0.3.3/scripts/verify_concordances.py#L183) is within 2 nested for-loops, and repeats for every pair of samples that need to be compared for concordance. This can take hours or days if there are hundreds of samples. Use Python threads to parallelize this. Start with investigating `multiprocessing.dummy` and if that doesn't work, look for something else.

**Comment by evanbiederstedt** [comment]
I think the first approach to first is to make it embarrassingly parallel. 

Please let us know the runtime for 200 samples with N threads. My understanding is that it's currently around 24 hours for ~200 samples. 

If I understand @allanbolipata correctly, it also does a matrix of all TN combinations. We could save time by doing only permutations (possibly).

**Comment by allanbolipata** [comment]
> We could save time by doing only permutations (possibly).

If by permutation you mean save time by doing not _all_ potential TN pairs and instead only a _select_ group of TN pairs to submit for `conpair`, I believe we can already do that - it's contingent upon the size of our tumor and normal lists, so we could just make a subset of whatever we're analyzing. In other words, we _could_ save time by not submitting every potential pair within our sample pairing "space" (if you will), but if we were to do that we would then be not submitting all possible combination which, if I understand `conpair` concordance correctly, is the point.

This is all assuming I understand what you meant by permutations, of course.

**Comment by evanbiederstedt** [comment]
I may have misunderstood what you meant by permutation vs combination. It's possible that there are no tricks possible.

**Comment by kpjonsson** [comment]
If sticking to the approach of only doing tumors against normals (and not all samples against each other) you can do one tumor sample against all normals in parallel. Then you'd have to gather that data for the purpose of visualization.

**Comment by evanbiederstedt** [comment]
> If sticking to the approach of only doing tumors against normals (and not all samples against each other) you can do one tumor sample against all normals in parallel. 

That's a good idea

> Then you'd have to gather that data for the purpose of visualization.

There are many SO topics on this sort of issue: https://stackoverflow.com/questions/33550312/multiprocessing-writing-to-pandas-dataframe

**Comment by evanbiederstedt** [comment]
Brainstorming how to make this more efficient:

Not really modern Python code here at all. 

Let's walk through this:

https://github.com/nygenome/Conpair/blob/master/scripts/verify_concordance.py#L64-L79

The "file parser" is here:
https://github.com/nygenome/Conpair/blob/master/modules/ContaminationMarker.py#L35-L47
https://github.com/nygenome/Conpair/blob/master/scripts/verify_concordance.py#L55

It's then a massive for loop here to count values in a list. 
https://github.com/nygenome/Conpair/blob/master/scripts/verify_concordance.py#L64-L79

That will take a long time. Each element is fed into this: 
https://github.com/nygenome/Conpair/blob/master/modules/ContaminationMarker.py#L98-L133

Which is two for loops to feed into this:
https://github.com/nygenome/Conpair/blob/master/modules/Genotypes.py#L34-L54

Which is multiple for loops. 

My conclusion is that everything in this is using standard Python data structures. The code was written just like C in 1985. 

We shouldn't begin with `multiprocessing`. 

We should try to parallelize with numba and `@jit(parallel=True)`. Refer to this, e.g. https://numba.pydata.org/numba-doc/dev/user/parallel.html

That should do what we need.

**Comment by stevekm** [comment]
this is added in the `dev` branch. There are two levels of parallelization. First, `run.py` can operate with `multiprocessing` on all combinations of tumor and normal files supplied in parallel with as many threads as desired. Combine this with pre-processing to use genotype likelihood pickles instead of calculating likelihoods from pileup for every combination, and you can get ~50,000 tumor-normal pair comparisons completed in ~8 minutes at 32 threads. Memory usage is minimal, <2GB in most cases we've seen so far.

The next level of parallelization comes from using the included workflow to submit HPC jobs for each tumor vs. all normals at 32 threads each. Depending on HPC traffic, its possible to get about 8 million tumor-normal pairs compared in about 20 minutes. This should be able to scale horizontally for as much HPC resources we have to throw at it.

This is only for concordance. Contamination has not been addressed yet, it appears to take about 50x longer to run so divide those numbers by 50 for a rought ballpark estimate of how long that would take.

**Comment by stevekm** [comment]
also worth noting that I tried to parallelize further on a per-marker basis (tumor * normal * marker region) but encountered a massive drop in throughput, not really sure why, I read some stuff online about Python mutexes on shared objects in memory which seemed like it could be coming into play.

**Comment by evanbiederstedt** [comment]
We realized a year ago that this was a pointless task (as it's not computational tractable to use on these many samples), and it embarrasses me that people are still talking about it. 

Last time I heard, there was this: https://github.com/brentp/somalier

Anyways, this just goes to show why doing cancer genomics at MSK is such a joke.
