### ISSUE TITLE
Major and minor contamination

### ISSUE THREAD

**Issue by evanbiederstedt** [mskcc/Conpair#4]
From @kpjonsson 

"Minor allele contamination" is estimated from minor allele frequencies at heterozygous SNPs. We should be able to get this out of Conpair. As well, we should be able to derive `major contam` from Conpair output–this is based on the fraction of heterozygous SNPs in a sample. Note that–I think–both of these metrics are based on a predefined list of fingerprinting SNPs, maybe Roslin uses some version of this.

It's possible we should just incorporate this in the current set of scripts.

**Comment by ckandoth** [comment]
Major/minor contamination metrics as developed by DMP and inherited by Roslin cannot and should not be part of Conpair.

**Comment by evanbiederstedt** [comment]
> Major/minor contamination metrics as developed by DMP and inherited by Roslin 

I'm a bit confused how the DMP and Roslin bit fits into this. Could you expand?

**Comment by ckandoth** [comment]
Sorry, let's leave this issue open till we figure out where this code should go. My first thought was https://github.com/mskcc/roslin-qc which is a whole lot of scripts that Roslin inherited from DMP. But we want to either obsolete or refactor that.

**Comment by evanbiederstedt** [comment]
Yeah, I'm not sure what the best approach is. 

Options could be separate branches for tools (and separate release strategies) given the same repo, or different repos given how the tools are tailored. 

> Options could be separate branches for tools (and separate release strategies)

I guess if tool A is used in two distinct ways, then two repos would make the most sense.

**Comment by stevekm** [comment]
dont think this is still needed?

**Comment by evanbiederstedt** [comment]
This brings back bad memories, and was a joke. 

Again, just another example of incompetence at MSK, and wasted time in my life.
