### ISSUE TITLE
pairing.txt

### ISSUE THREAD

**Issue by ait5** [mskcc/Conpair#5]
Hi, do you have any example of 'pairing.txt' file for concordance script? Should that be a tab-separated file with full path to pileup files or just sample names?

Thanks!

**Comment by ait5** [comment]
Already working with tab-separated file with normal and tumor SampleID

**Comment by evanbiederstedt** [comment]
Hi there @ait5

As an another example, it's not entirely clear what you're discussing in this issue, or how users/developers could help response. 

I roughly know about you're discussing though----yes, this tab-delimited file with tumor and normal IDs should work.
