### ISSUE TITLE
IndexError: list index out of range for MARKER_FILE

### ISSUE THREAD

**Issue by ait5** [mskcc/Conpair#6]
When running `verify_concordances.py`script, using same marker-file from pileup script, error is printed
```
File "Conpair/scripts/verify_concordances.py", line 217, in run_verify_concordance
    Markers = get_markers(MARKER_FILE)
  File "Conpair/modules/ContaminationMarker.py", line 44, in get_markers
    M = Marker(line[0], line[1], line[2], line[3], float(line[4]))
```

Marker file has 5 columns... that should work, should not it?

**Comment by evanbiederstedt** [comment]
Hi @ait5 

It's difficult to debug these without seeing (at least partially) the inputs you're using. 

> Marker file has 5 columns... that should work, should not it?

I mean, yes...but then again, maybe there's some other character in the input file screwing up the python parser. Without something more to work with, I'm just guessing. 

I should also mention the majority of this code was written at https://github.com/nygenome/Conpair, which modifications at this local forked branch by @Zuojian-Tang...so it's possible some of these issues may need to be directed to the NYGC folks. 

All that being said, there are other tools which do something similar to Conpair---depending on your goals, you may want to play with those. 

Thanks, Evan

**Comment by ait5** [comment]
Hi Evan,

I have also tried markers.bed file with just three rows (as it is the case for markers in Conpair/data/markers):

> 1	35013536	35013636
1	158507134	158507234
10	18471911	18472011
10	60277499	60277599
11	74401713	74401813
11	110697255	110697355
12	17903294	17903394
12	22968328	22968428
13	76833634	76833734
13	103337307	103337407

The thing is that I am trying to match WES bams with IMPACT panel bams with the specific positions from marker.file

**Comment by evanbiederstedt** [comment]
Hi @ait5 

The function in question is here: 

https://github.com/mskcc/Conpair/blob/master/modules/ContaminationMarker.py#L35-L47

```
def get_markers(marker_file):
    Marker_Set = OrderedDict()
    if not os.path.isfile(marker_file):
        sys.stderr.write("The specified marker file cannot be find: " + marker_file)
    markers = open(marker_file)
    for line in markers:
        if "#" in line:
            continue
        line = line.split()
        M = Marker(line[0], line[1], line[2], line[3], float(line[4]))
        Marker_Set[line[0] + ":" + line[1]] = M
    markers.close()
    return(Marker_Set)

```

You'll probably need to do a bit more debugging with the python code itself to figure out precisely where the issue is. It's getting stuck somewhere in the internal logic of these parsers. 

I'm happy to help out further on this front, but that's best done over e-mail threads with e.g. MFB et al CC'ed. (I'm also happy to go away of course.)

**Comment by stevekm** [comment]
The pileup scripts use a .bed file. The concordance scripts use a .txt file which is essentially a .bed file with genotype likelihoods in the 5th column (@svural is that right?)

so you are probably using the wrong file.
