### ISSUE TITLE
Update estimate_tumor_normal_contaminations.py to take inputs from a file instead of command line parameters

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/Conpair#7]
Currently conpair uses separate flags for tumor and normal pileup files (https://github.com/mskcc/Conpair/blob/master/scripts/estimate_tumor_normal_contaminations.py#L49-L50); this causes the command to get too large for command line and singularity when there are a lot of samples, breaking operation.

Update it so that it takes in an input file containing references to the pileup files instead.

@timosong please clarify any issues here. Alternative suggestions are also welcome.

**Comment by stevekm** [comment]
this should be resolved in the new `dev` branch
Right now, that implementation is using two files, `tumors.txt` and `normals.txt`, with lists of file paths to the input files.
